CREATE TABLE ACCOUNT
(
    ID       INT PRIMARY KEY AUTO_INCREMENT,
    IBAN     VARCHAR(28)                                   NOT NULL,
    UNIQUE (IBAN),
    CURRENCY ENUM ('EUR', 'GBP', 'USD', 'BTC')             NOT NULL,
    BALANCE  DECIMAL(11, 2) DEFAULT 0 CHECK (BALANCE >= 0) NOT NULL
);

CREATE TABLE TRANSACTION
(
    ID              INT PRIMARY KEY AUTO_INCREMENT,
    AMOUNT          DECIMAL(11, 2) CHECK (AMOUNT > 0),
    FROM_ACCOUNT_ID INT,
    TO_ACCOUNT_ID   INT,
    TIMESTAMP       TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),

    FOREIGN KEY (FROM_ACCOUNT_ID) REFERENCES ACCOUNT (ID),
    FOREIGN KEY (TO_ACCOUNT_ID) REFERENCES ACCOUNT (ID),

    CONSTRAINT ACCOUNTS_NOT_EQUAL CHECK (FROM_ACCOUNT_ID != TO_ACCOUNT_ID)
);